{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "f06bc0f6-7cd2-47e6-b745-aafbaf999d7c",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Columns kept for clustering:\n",
      "Index(['B', 'C', 'L', 'S', 'S*', 'Sa', 'V', 'nuts', 'tangy', 'bland',\n",
      "       'chemical', 'orange', 'green', 'rubber', 'marshmallow', 'basic cocoa',\n",
      "       'burnt', 'muted', 'citrus', 'coarse', 'red berry', 'off notes',\n",
      "       'black pepper', 'bold', 'mild bitter', 'hammy', 'strawberry', 'smooth',\n",
      "       'dirty', 'rubbery', 'mild fruit', 'melon', 'metallic', 'nut', 'honey',\n",
      "       'tobacco', 'smoke', 'vegetal', 'pungent', 'off', 'cherry', 'smokey',\n",
      "       'acidic', 'astringent', 'banana', 'brownie', 'oily', 'dairy', 'complex',\n",
      "       'rich cocoa', 'fruity', 'dry', 'gritty', 'spice', 'grassy', 'tart',\n",
      "       'bitter', 'caramel', 'rich', 'coffee', 'dried fruit', 'sticky',\n",
      "       'vanilla', 'woody', 'molasses', 'fruit', 'intense', 'spicy', 'sour',\n",
      "       'floral', 'sandy', 'fatty', 'creamy', 'earthy', 'roasty', 'nutty',\n",
      "       'cocoa', 'sweet'],\n",
      "      dtype='object')\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>B</th>\n",
       "      <th>C</th>\n",
       "      <th>L</th>\n",
       "      <th>S</th>\n",
       "      <th>S*</th>\n",
       "      <th>Sa</th>\n",
       "      <th>V</th>\n",
       "      <th>nuts</th>\n",
       "      <th>tangy</th>\n",
       "      <th>bland</th>\n",
       "      <th>...</th>\n",
       "      <th>sour</th>\n",
       "      <th>floral</th>\n",
       "      <th>sandy</th>\n",
       "      <th>fatty</th>\n",
       "      <th>creamy</th>\n",
       "      <th>earthy</th>\n",
       "      <th>roasty</th>\n",
       "      <th>nutty</th>\n",
       "      <th>cocoa</th>\n",
       "      <th>sweet</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2784</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2785</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2786</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2787</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2788</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>2789 rows × 78 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "      B  C  L  S  S*  Sa  V  nuts  tangy  bland  ...  sour  floral  sandy  \\\n",
       "0     1  1  0  1   0   0  0     0      0      0  ...     0       0      0   \n",
       "1     1  1  0  1   0   0  0     0      0      0  ...     0       0      0   \n",
       "2     1  1  0  1   0   0  0     0      0      0  ...     0       0      0   \n",
       "3     1  1  0  1   0   0  0     0      0      0  ...     0       0      0   \n",
       "4     1  1  0  1   0   0  0     0      0      0  ...     0       0      0   \n",
       "...  .. .. .. ..  ..  .. ..   ...    ...    ...  ...   ...     ...    ...   \n",
       "2784  1  1  0  0   1   1  0     0      0      0  ...     0       0      0   \n",
       "2785  1  1  0  1   0   0  0     0      0      0  ...     0       0      0   \n",
       "2786  1  1  0  1   0   0  0     0      0      0  ...     0       0      0   \n",
       "2787  1  1  0  1   0   0  0     0      0      0  ...     0       0      0   \n",
       "2788  1  1  0  1   0   0  0     0      0      0  ...     0       0      0   \n",
       "\n",
       "      fatty  creamy  earthy  roasty  nutty  cocoa  sweet  \n",
       "0         0       0       0       0      0      1      0  \n",
       "1         0       0       0       0      0      1      0  \n",
       "2         1       0       0       0      0      0      0  \n",
       "3         0       0       0       0      0      0      0  \n",
       "4         1       0       0       0      0      0      0  \n",
       "...     ...     ...     ...     ...    ...    ...    ...  \n",
       "2784      0       0       0       0      0      0      0  \n",
       "2785      0       0       0       0      0      0      0  \n",
       "2786      0       0       0       1      0      0      0  \n",
       "2787      1       0       0       0      0      0      0  \n",
       "2788      1       0       1       0      0      1      0  \n",
       "\n",
       "[2789 rows x 78 columns]"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import pandas as pd\n",
    "\n",
    "# Step 1: Load data\n",
    "df = pd.read_csv(r\"C:\\Users\\akank\\homework\\hw1\\data\\data_reduced_2025_flavors_of_cacao.csv\", index_col=0)\n",
    "\n",
    "# Step 2: Drop unnecessary metadata columns\n",
    "ignore_cols = [0,1,2,3,4,5,6,7,15]\n",
    "df_cluster = df.drop(df.columns[ignore_cols], axis=1)\n",
    "\n",
    "# Step 3: Check what columns are left\n",
    "print(\"Columns kept for clustering:\")\n",
    "print(df_cluster.columns)\n",
    "\n",
    "# Step 4: View the top of the clusterable data\n",
    "df_cluster\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "7f4394d9-4906-48f8-b00c-5b6738af0c39",
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.cluster import KMeans\n",
    "\n",
    "# PERFORM KMEANS K=2\n",
    "kmeans        = KMeans(n_clusters=2, random_state=0, n_init=\"auto\").fit(df_cluster)\n",
    "\n",
    "# ASSIGN CLUSTER NUMBER IN DF\n",
    "df['cluster'] = kmeans.predict(df_cluster)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "11456612-3838-4909-bfce-0f1f6c428e64",
   "metadata": {},
   "outputs": [],
   "source": [
    "def generate_cluster_report(k, d):\n",
    "    print(f\"CLUSTER {k} SUMMARY\")\n",
    "\n",
    "    print(f\"Mean Rating: {d['Rating'].mean():.3f}\")\n",
    "\n",
    "    print(f\"Mean Cocoa %: {d['Cocoa Percent'].mean()*100:.2f}%\")\n",
    "    \n",
    "    print(\"Median review date:\", int(d['Review Date'].median()) )\n",
    "    \n",
    "    print(\"Top 5 Bean Origins\")\n",
    "    for c, v in d['Country of Bean Origin'].value_counts(ascending=False).nlargest(5).items():\n",
    "        print(\"    \", c, \"...\", v)\n",
    "\n",
    "    print(\"Top 5 Company Locations\")\n",
    "    for c, v in d['Company Location'].value_counts(ascending=False).nlargest(5).items():\n",
    "        print(\"    \", c, \"...\", v)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "ced92ec8-8029-42ee-8fa6-9dfbc5aac9c5",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "CLUSTER 0 SUMMARY\n",
      "Mean Rating: 3.213\n",
      "Mean Cocoa %: 71.13%\n",
      "Median review date: 2015\n",
      "Top 5 Bean Origins\n",
      "     Venezuela ... 192\n",
      "     Peru ... 181\n",
      "     Ecuador ... 152\n",
      "     Dominican Republic ... 138\n",
      "     Madagascar ... 122\n",
      "Top 5 Company Locations\n",
      "     U.S.A. ... 723\n",
      "     France ... 167\n",
      "     Canada ... 138\n",
      "     U.K. ... 108\n",
      "     Belgium ... 71\n",
      "\n",
      "====\n",
      "\n",
      "CLUSTER 1 SUMMARY\n",
      "Mean Rating: 3.166\n",
      "Mean Cocoa %: 72.46%\n",
      "Median review date: 2015\n",
      "Top 5 Bean Origins\n",
      "     Dominican Republic ... 107\n",
      "     Peru ... 95\n",
      "     Ecuador ... 78\n",
      "     Venezuela ... 75\n",
      "     Madagascar ... 72\n",
      "Top 5 Company Locations\n",
      "     U.S.A. ... 537\n",
      "     Canada ... 50\n",
      "     Italy ... 40\n",
      "     U.K. ... 27\n",
      "     France ... 20\n"
     ]
    }
   ],
   "source": [
    "# generate report for data assigned cluster 0\n",
    "generate_cluster_report( 0, df.iloc[:,:8].loc[df.cluster==0] )\n",
    "print(\"\\n====\\n\")\n",
    "\n",
    "# generate the report for data assigned cluster 1\n",
    "generate_cluster_report( 1, df.iloc[:,:8].loc[df.cluster==1] )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "5a1635d3-0a71-46a3-949b-a1bc8d5a21cc",
   "metadata": {},
   "outputs": [],
   "source": [
    "'''\n",
    "    Return the domininant characteristics of the cluster.\n",
    "\n",
    "        thresh : the number of characteristics to limit to\n",
    "'''\n",
    "def get_cluster_characteristics(centers, columns, thresh=10):\n",
    "    return \\\n",
    "        pd.DataFrame(centers, index=columns).nlargest(thresh, columns=0).index.to_list()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "ef873d66-af7d-4969-8847-16bc07563018",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "['B', 'C', 'S', 'L', 'V', 'sweet', 'nutty', 'cocoa', 'fatty', 'creamy']"
      ]
     },
     "execution_count": 13,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# top 10 dominant characteristics for cluster 0\n",
    "get_cluster_characteristics(kmeans.cluster_centers_[0], df_cluster.columns)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "b44ebcfd-663a-4fc4-b868-8ee30453e8c0",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "['B',\n",
       " 'S',\n",
       " 'cocoa',\n",
       " 'roasty',\n",
       " 'earthy',\n",
       " 'nutty',\n",
       " 'intense',\n",
       " 'sour',\n",
       " 'sweet',\n",
       " 'spicy']"
      ]
     },
     "execution_count": 14,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# top 10 dominant characteristics for cluster 1\n",
    "get_cluster_characteristics(kmeans.cluster_centers_[1], df_cluster.columns)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "e1723db1-34f3-40b2-918c-b4fe14c9c571",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Top 10 dominant characteristics for Cluster 0:\n",
      "['B', 'C', 'S', 'L', 'sweet', 'nutty', 'cocoa', 'fatty', 'roasty', 'creamy']\n",
      "\n",
      "=====\n",
      "\n",
      "Top 10 dominant characteristics for Cluster 1:\n",
      "['B', 'S', 'cocoa', 'roasty', 'sour', 'sweet', 'intense', 'fruit', 'spicy', 'floral']\n",
      "\n",
      "=====\n",
      "\n",
      "Top 10 dominant characteristics for Cluster 2:\n",
      "['B', 'S', 'earthy', 'nutty', 'roasty', 'intense', 'C', 'sandy', 'cocoa', 'spicy']\n",
      "\n",
      "=====\n",
      "\n",
      "Top 10 dominant characteristics for Cluster 3:\n",
      "['B', 'V', 'C', 'S', 'L', 'vanilla', 'sweet', 'creamy', 'cocoa', 'nutty']\n",
      "\n",
      "=====\n",
      "\n",
      "Top 10 dominant characteristics for Cluster 4:\n",
      "['B', 'C', 'S', 'banana', 'dairy', 'L', 'nutty', 'sweet', 'cocoa', 'caramel']\n",
      "\n",
      "=====\n",
      "\n"
     ]
    }
   ],
   "source": [
    "for i in range(5):  # loop over 0,1,2,3,4\n",
    "    print(f\"Top 10 dominant characteristics for Cluster {i}:\")\n",
    "    print(get_cluster_characteristics(kmeans5.cluster_centers_[i], df_cluster.columns))\n",
    "    print(\"\\n=====\\n\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "6f2e1cae-99fd-4ae4-bd29-b50d7986c166",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "CLUSTER 2 SUMMARY\n",
      "Mean Rating: 3.125\n",
      "Mean Cocoa %: 72.47%\n",
      "Median review date: 2016\n",
      "Top 5 Bean Origins\n",
      "     Venezuela ... 36\n",
      "     Dominican Republic ... 25\n",
      "     Ecuador ... 15\n",
      "     Nicaragua ... 10\n",
      "     Peru ... 8\n",
      "Top 5 Company Locations\n",
      "     U.S.A. ... 99\n",
      "     Canada ... 12\n",
      "     Venezuela ... 8\n",
      "     Italy ... 6\n",
      "     U.K. ... 6\n",
      "CLUSTER 3 SUMMARY\n",
      "Mean Rating: 3.032\n",
      "Mean Cocoa %: 69.91%\n",
      "Median review date: 2010\n",
      "Top 5 Bean Origins\n",
      "     Blend ... 61\n",
      "     Venezuela ... 48\n",
      "     Ecuador ... 28\n",
      "     Dominican Republic ... 28\n",
      "     Madagascar ... 26\n",
      "Top 5 Company Locations\n",
      "     U.S.A. ... 165\n",
      "     France ... 49\n",
      "     Belgium ... 20\n",
      "     Italy ... 17\n",
      "     Canada ... 11\n",
      "CLUSTER 4 SUMMARY\n",
      "Mean Rating: 3.434\n",
      "Mean Cocoa %: 69.47%\n",
      "Median review date: 2015\n",
      "Top 5 Bean Origins\n",
      "     Ecuador ... 8\n",
      "     Dominican Republic ... 7\n",
      "     Brazil ... 6\n",
      "     Venezuela ... 5\n",
      "     Peru ... 5\n",
      "Top 5 Company Locations\n",
      "     U.S.A. ... 23\n",
      "     Canada ... 6\n",
      "     Brazil ... 5\n",
      "     U.K. ... 4\n",
      "     France ... 4\n"
     ]
    }
   ],
   "source": [
    "generate_cluster_report(2, df[df['cluster_5']==2])\n",
    "generate_cluster_report(3, df[df['cluster_5']==3])\n",
    "generate_cluster_report(4, df[df['cluster_5']==4])\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "id": "cb425337-f892-4b37-ab64-f9e31b7b1527",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "CLUSTER 7 SUMMARY\n",
      "Mean Rating: 3.041\n",
      "Mean Cocoa %: 70.02%\n",
      "Median review date: 2010\n",
      "Top 5 Bean Origins\n",
      "     Blend ... 53\n",
      "     Venezuela ... 42\n",
      "     Madagascar ... 25\n",
      "     Dominican Republic ... 25\n",
      "     Ecuador ... 20\n",
      "Top 5 Company Locations\n",
      "     U.S.A. ... 138\n",
      "     France ... 43\n",
      "     Belgium ... 20\n",
      "     Italy ... 11\n",
      "     Japan ... 10\n",
      "CLUSTER 10 SUMMARY\n",
      "Mean Rating: 3.389\n",
      "Mean Cocoa %: 71.17%\n",
      "Median review date: 2018\n",
      "Top 5 Bean Origins\n",
      "     Dominican Republic ... 22\n",
      "     Peru ... 17\n",
      "     Belize ... 14\n",
      "     Madagascar ... 12\n",
      "     Guatemala ... 12\n",
      "Top 5 Company Locations\n",
      "     U.S.A. ... 100\n",
      "     France ... 13\n",
      "     Canada ... 13\n",
      "     U.K. ... 7\n",
      "     Italy ... 4\n"
     ]
    }
   ],
   "source": [
    "generate_cluster_report(7, df[df['cluster_8']==7])\n",
    "generate_cluster_report(10, df[df['cluster_11']==10])\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "id": "3a3f7c4a-8f8c-47f4-a0f3-1c90152f4fe3",
   "metadata": {},
   "outputs": [],
   "source": [
    "df_train = pd.read_csv(r\"C:\\Users\\akank\\homework\\hw1\\data\\train.csv\", index_col=0)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "id": "60516c93-c45f-4fb3-b13d-31687bc146ff",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>B</th>\n",
       "      <th>C</th>\n",
       "      <th>L</th>\n",
       "      <th>S</th>\n",
       "      <th>S*</th>\n",
       "      <th>Sa</th>\n",
       "      <th>V</th>\n",
       "      <th>nuts</th>\n",
       "      <th>tangy</th>\n",
       "      <th>bland</th>\n",
       "      <th>...</th>\n",
       "      <th>floral</th>\n",
       "      <th>sandy</th>\n",
       "      <th>fatty</th>\n",
       "      <th>creamy</th>\n",
       "      <th>earthy</th>\n",
       "      <th>roasty</th>\n",
       "      <th>nutty</th>\n",
       "      <th>cocoa</th>\n",
       "      <th>sweet</th>\n",
       "      <th>cluster</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>615</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1807</th>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>125</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1576</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>231</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2629</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1959</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2272</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>3</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>737</th>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2482</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>10 rows × 79 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "      B  C  L  S  S*  Sa  V  nuts  tangy  bland  ...  floral  sandy  fatty  \\\n",
       "615   1  1  1  1   0   0  0     0      0      0  ...       0      0      0   \n",
       "1807  1  0  0  1   0   0  0     0      0      0  ...       0      0      0   \n",
       "125   1  1  1  1   0   0  0     0      0      0  ...       0      0      0   \n",
       "1576  1  1  0  1   0   0  0     0      0      0  ...       0      0      1   \n",
       "231   1  1  0  1   0   0  0     0      0      0  ...       0      0      0   \n",
       "2629  1  1  0  1   0   0  0     0      0      0  ...       0      0      0   \n",
       "1959  1  1  0  1   0   0  0     0      0      0  ...       0      0      0   \n",
       "2272  1  1  1  1   0   0  1     0      0      0  ...       0      0      0   \n",
       "737   1  0  0  1   0   0  0     0      0      0  ...       0      0      0   \n",
       "2482  1  1  0  1   0   0  0     0      0      0  ...       0      0      0   \n",
       "\n",
       "      creamy  earthy  roasty  nutty  cocoa  sweet  cluster  \n",
       "615        0       0       0      0      1      0        0  \n",
       "1807       0       0       0      0      0      1        1  \n",
       "125        0       0       0      0      0      1        0  \n",
       "1576       0       0       0      0      1      0        0  \n",
       "231        0       0       0      0      0      0        0  \n",
       "2629       0       0       0      0      0      0        0  \n",
       "1959       0       0       0      0      0      0        0  \n",
       "2272       0       0       0      0      0      0        3  \n",
       "737        0       0       0      0      0      0        1  \n",
       "2482       0       0       1      1      0      1        0  \n",
       "\n",
       "[10 rows x 79 columns]"
      ]
     },
     "execution_count": 26,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df_train"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "id": "76423040-c8c1-43d8-9514-a318924311b9",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<style>#sk-container-id-1 {\n",
       "  /* Definition of color scheme common for light and dark mode */\n",
       "  --sklearn-color-text: #000;\n",
       "  --sklearn-color-text-muted: #666;\n",
       "  --sklearn-color-line: gray;\n",
       "  /* Definition of color scheme for unfitted estimators */\n",
       "  --sklearn-color-unfitted-level-0: #fff5e6;\n",
       "  --sklearn-color-unfitted-level-1: #f6e4d2;\n",
       "  --sklearn-color-unfitted-level-2: #ffe0b3;\n",
       "  --sklearn-color-unfitted-level-3: chocolate;\n",
       "  /* Definition of color scheme for fitted estimators */\n",
       "  --sklearn-color-fitted-level-0: #f0f8ff;\n",
       "  --sklearn-color-fitted-level-1: #d4ebff;\n",
       "  --sklearn-color-fitted-level-2: #b3dbfd;\n",
       "  --sklearn-color-fitted-level-3: cornflowerblue;\n",
       "\n",
       "  /* Specific color for light theme */\n",
       "  --sklearn-color-text-on-default-background: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, black)));\n",
       "  --sklearn-color-background: var(--sg-background-color, var(--theme-background, var(--jp-layout-color0, white)));\n",
       "  --sklearn-color-border-box: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, black)));\n",
       "  --sklearn-color-icon: #696969;\n",
       "\n",
       "  @media (prefers-color-scheme: dark) {\n",
       "    /* Redefinition of color scheme for dark theme */\n",
       "    --sklearn-color-text-on-default-background: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, white)));\n",
       "    --sklearn-color-background: var(--sg-background-color, var(--theme-background, var(--jp-layout-color0, #111)));\n",
       "    --sklearn-color-border-box: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, white)));\n",
       "    --sklearn-color-icon: #878787;\n",
       "  }\n",
       "}\n",
       "\n",
       "#sk-container-id-1 {\n",
       "  color: var(--sklearn-color-text);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 pre {\n",
       "  padding: 0;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 input.sk-hidden--visually {\n",
       "  border: 0;\n",
       "  clip: rect(1px 1px 1px 1px);\n",
       "  clip: rect(1px, 1px, 1px, 1px);\n",
       "  height: 1px;\n",
       "  margin: -1px;\n",
       "  overflow: hidden;\n",
       "  padding: 0;\n",
       "  position: absolute;\n",
       "  width: 1px;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-dashed-wrapped {\n",
       "  border: 1px dashed var(--sklearn-color-line);\n",
       "  margin: 0 0.4em 0.5em 0.4em;\n",
       "  box-sizing: border-box;\n",
       "  padding-bottom: 0.4em;\n",
       "  background-color: var(--sklearn-color-background);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-container {\n",
       "  /* jupyter's `normalize.less` sets `[hidden] { display: none; }`\n",
       "     but bootstrap.min.css set `[hidden] { display: none !important; }`\n",
       "     so we also need the `!important` here to be able to override the\n",
       "     default hidden behavior on the sphinx rendered scikit-learn.org.\n",
       "     See: https://github.com/scikit-learn/scikit-learn/issues/21755 */\n",
       "  display: inline-block !important;\n",
       "  position: relative;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-text-repr-fallback {\n",
       "  display: none;\n",
       "}\n",
       "\n",
       "div.sk-parallel-item,\n",
       "div.sk-serial,\n",
       "div.sk-item {\n",
       "  /* draw centered vertical line to link estimators */\n",
       "  background-image: linear-gradient(var(--sklearn-color-text-on-default-background), var(--sklearn-color-text-on-default-background));\n",
       "  background-size: 2px 100%;\n",
       "  background-repeat: no-repeat;\n",
       "  background-position: center center;\n",
       "}\n",
       "\n",
       "/* Parallel-specific style estimator block */\n",
       "\n",
       "#sk-container-id-1 div.sk-parallel-item::after {\n",
       "  content: \"\";\n",
       "  width: 100%;\n",
       "  border-bottom: 2px solid var(--sklearn-color-text-on-default-background);\n",
       "  flex-grow: 1;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-parallel {\n",
       "  display: flex;\n",
       "  align-items: stretch;\n",
       "  justify-content: center;\n",
       "  background-color: var(--sklearn-color-background);\n",
       "  position: relative;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-parallel-item {\n",
       "  display: flex;\n",
       "  flex-direction: column;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-parallel-item:first-child::after {\n",
       "  align-self: flex-end;\n",
       "  width: 50%;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-parallel-item:last-child::after {\n",
       "  align-self: flex-start;\n",
       "  width: 50%;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-parallel-item:only-child::after {\n",
       "  width: 0;\n",
       "}\n",
       "\n",
       "/* Serial-specific style estimator block */\n",
       "\n",
       "#sk-container-id-1 div.sk-serial {\n",
       "  display: flex;\n",
       "  flex-direction: column;\n",
       "  align-items: center;\n",
       "  background-color: var(--sklearn-color-background);\n",
       "  padding-right: 1em;\n",
       "  padding-left: 1em;\n",
       "}\n",
       "\n",
       "\n",
       "/* Toggleable style: style used for estimator/Pipeline/ColumnTransformer box that is\n",
       "clickable and can be expanded/collapsed.\n",
       "- Pipeline and ColumnTransformer use this feature and define the default style\n",
       "- Estimators will overwrite some part of the style using the `sk-estimator` class\n",
       "*/\n",
       "\n",
       "/* Pipeline and ColumnTransformer style (default) */\n",
       "\n",
       "#sk-container-id-1 div.sk-toggleable {\n",
       "  /* Default theme specific background. It is overwritten whether we have a\n",
       "  specific estimator or a Pipeline/ColumnTransformer */\n",
       "  background-color: var(--sklearn-color-background);\n",
       "}\n",
       "\n",
       "/* Toggleable label */\n",
       "#sk-container-id-1 label.sk-toggleable__label {\n",
       "  cursor: pointer;\n",
       "  display: flex;\n",
       "  width: 100%;\n",
       "  margin-bottom: 0;\n",
       "  padding: 0.5em;\n",
       "  box-sizing: border-box;\n",
       "  text-align: center;\n",
       "  align-items: start;\n",
       "  justify-content: space-between;\n",
       "  gap: 0.5em;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 label.sk-toggleable__label .caption {\n",
       "  font-size: 0.6rem;\n",
       "  font-weight: lighter;\n",
       "  color: var(--sklearn-color-text-muted);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 label.sk-toggleable__label-arrow:before {\n",
       "  /* Arrow on the left of the label */\n",
       "  content: \"▸\";\n",
       "  float: left;\n",
       "  margin-right: 0.25em;\n",
       "  color: var(--sklearn-color-icon);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 label.sk-toggleable__label-arrow:hover:before {\n",
       "  color: var(--sklearn-color-text);\n",
       "}\n",
       "\n",
       "/* Toggleable content - dropdown */\n",
       "\n",
       "#sk-container-id-1 div.sk-toggleable__content {\n",
       "  max-height: 0;\n",
       "  max-width: 0;\n",
       "  overflow: hidden;\n",
       "  text-align: left;\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-0);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-toggleable__content.fitted {\n",
       "  /* fitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-0);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-toggleable__content pre {\n",
       "  margin: 0.2em;\n",
       "  border-radius: 0.25em;\n",
       "  color: var(--sklearn-color-text);\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-0);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-toggleable__content.fitted pre {\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-0);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 input.sk-toggleable__control:checked~div.sk-toggleable__content {\n",
       "  /* Expand drop-down */\n",
       "  max-height: 200px;\n",
       "  max-width: 100%;\n",
       "  overflow: auto;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 input.sk-toggleable__control:checked~label.sk-toggleable__label-arrow:before {\n",
       "  content: \"▾\";\n",
       "}\n",
       "\n",
       "/* Pipeline/ColumnTransformer-specific style */\n",
       "\n",
       "#sk-container-id-1 div.sk-label input.sk-toggleable__control:checked~label.sk-toggleable__label {\n",
       "  color: var(--sklearn-color-text);\n",
       "  background-color: var(--sklearn-color-unfitted-level-2);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-label.fitted input.sk-toggleable__control:checked~label.sk-toggleable__label {\n",
       "  background-color: var(--sklearn-color-fitted-level-2);\n",
       "}\n",
       "\n",
       "/* Estimator-specific style */\n",
       "\n",
       "/* Colorize estimator box */\n",
       "#sk-container-id-1 div.sk-estimator input.sk-toggleable__control:checked~label.sk-toggleable__label {\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-2);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-estimator.fitted input.sk-toggleable__control:checked~label.sk-toggleable__label {\n",
       "  /* fitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-2);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-label label.sk-toggleable__label,\n",
       "#sk-container-id-1 div.sk-label label {\n",
       "  /* The background is the default theme color */\n",
       "  color: var(--sklearn-color-text-on-default-background);\n",
       "}\n",
       "\n",
       "/* On hover, darken the color of the background */\n",
       "#sk-container-id-1 div.sk-label:hover label.sk-toggleable__label {\n",
       "  color: var(--sklearn-color-text);\n",
       "  background-color: var(--sklearn-color-unfitted-level-2);\n",
       "}\n",
       "\n",
       "/* Label box, darken color on hover, fitted */\n",
       "#sk-container-id-1 div.sk-label.fitted:hover label.sk-toggleable__label.fitted {\n",
       "  color: var(--sklearn-color-text);\n",
       "  background-color: var(--sklearn-color-fitted-level-2);\n",
       "}\n",
       "\n",
       "/* Estimator label */\n",
       "\n",
       "#sk-container-id-1 div.sk-label label {\n",
       "  font-family: monospace;\n",
       "  font-weight: bold;\n",
       "  display: inline-block;\n",
       "  line-height: 1.2em;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-label-container {\n",
       "  text-align: center;\n",
       "}\n",
       "\n",
       "/* Estimator-specific */\n",
       "#sk-container-id-1 div.sk-estimator {\n",
       "  font-family: monospace;\n",
       "  border: 1px dotted var(--sklearn-color-border-box);\n",
       "  border-radius: 0.25em;\n",
       "  box-sizing: border-box;\n",
       "  margin-bottom: 0.5em;\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-0);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-estimator.fitted {\n",
       "  /* fitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-0);\n",
       "}\n",
       "\n",
       "/* on hover */\n",
       "#sk-container-id-1 div.sk-estimator:hover {\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-2);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-estimator.fitted:hover {\n",
       "  /* fitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-2);\n",
       "}\n",
       "\n",
       "/* Specification for estimator info (e.g. \"i\" and \"?\") */\n",
       "\n",
       "/* Common style for \"i\" and \"?\" */\n",
       "\n",
       ".sk-estimator-doc-link,\n",
       "a:link.sk-estimator-doc-link,\n",
       "a:visited.sk-estimator-doc-link {\n",
       "  float: right;\n",
       "  font-size: smaller;\n",
       "  line-height: 1em;\n",
       "  font-family: monospace;\n",
       "  background-color: var(--sklearn-color-background);\n",
       "  border-radius: 1em;\n",
       "  height: 1em;\n",
       "  width: 1em;\n",
       "  text-decoration: none !important;\n",
       "  margin-left: 0.5em;\n",
       "  text-align: center;\n",
       "  /* unfitted */\n",
       "  border: var(--sklearn-color-unfitted-level-1) 1pt solid;\n",
       "  color: var(--sklearn-color-unfitted-level-1);\n",
       "}\n",
       "\n",
       ".sk-estimator-doc-link.fitted,\n",
       "a:link.sk-estimator-doc-link.fitted,\n",
       "a:visited.sk-estimator-doc-link.fitted {\n",
       "  /* fitted */\n",
       "  border: var(--sklearn-color-fitted-level-1) 1pt solid;\n",
       "  color: var(--sklearn-color-fitted-level-1);\n",
       "}\n",
       "\n",
       "/* On hover */\n",
       "div.sk-estimator:hover .sk-estimator-doc-link:hover,\n",
       ".sk-estimator-doc-link:hover,\n",
       "div.sk-label-container:hover .sk-estimator-doc-link:hover,\n",
       ".sk-estimator-doc-link:hover {\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-3);\n",
       "  color: var(--sklearn-color-background);\n",
       "  text-decoration: none;\n",
       "}\n",
       "\n",
       "div.sk-estimator.fitted:hover .sk-estimator-doc-link.fitted:hover,\n",
       ".sk-estimator-doc-link.fitted:hover,\n",
       "div.sk-label-container:hover .sk-estimator-doc-link.fitted:hover,\n",
       ".sk-estimator-doc-link.fitted:hover {\n",
       "  /* fitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-3);\n",
       "  color: var(--sklearn-color-background);\n",
       "  text-decoration: none;\n",
       "}\n",
       "\n",
       "/* Span, style for the box shown on hovering the info icon */\n",
       ".sk-estimator-doc-link span {\n",
       "  display: none;\n",
       "  z-index: 9999;\n",
       "  position: relative;\n",
       "  font-weight: normal;\n",
       "  right: .2ex;\n",
       "  padding: .5ex;\n",
       "  margin: .5ex;\n",
       "  width: min-content;\n",
       "  min-width: 20ex;\n",
       "  max-width: 50ex;\n",
       "  color: var(--sklearn-color-text);\n",
       "  box-shadow: 2pt 2pt 4pt #999;\n",
       "  /* unfitted */\n",
       "  background: var(--sklearn-color-unfitted-level-0);\n",
       "  border: .5pt solid var(--sklearn-color-unfitted-level-3);\n",
       "}\n",
       "\n",
       ".sk-estimator-doc-link.fitted span {\n",
       "  /* fitted */\n",
       "  background: var(--sklearn-color-fitted-level-0);\n",
       "  border: var(--sklearn-color-fitted-level-3);\n",
       "}\n",
       "\n",
       ".sk-estimator-doc-link:hover span {\n",
       "  display: block;\n",
       "}\n",
       "\n",
       "/* \"?\"-specific style due to the `<a>` HTML tag */\n",
       "\n",
       "#sk-container-id-1 a.estimator_doc_link {\n",
       "  float: right;\n",
       "  font-size: 1rem;\n",
       "  line-height: 1em;\n",
       "  font-family: monospace;\n",
       "  background-color: var(--sklearn-color-background);\n",
       "  border-radius: 1rem;\n",
       "  height: 1rem;\n",
       "  width: 1rem;\n",
       "  text-decoration: none;\n",
       "  /* unfitted */\n",
       "  color: var(--sklearn-color-unfitted-level-1);\n",
       "  border: var(--sklearn-color-unfitted-level-1) 1pt solid;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 a.estimator_doc_link.fitted {\n",
       "  /* fitted */\n",
       "  border: var(--sklearn-color-fitted-level-1) 1pt solid;\n",
       "  color: var(--sklearn-color-fitted-level-1);\n",
       "}\n",
       "\n",
       "/* On hover */\n",
       "#sk-container-id-1 a.estimator_doc_link:hover {\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-3);\n",
       "  color: var(--sklearn-color-background);\n",
       "  text-decoration: none;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 a.estimator_doc_link.fitted:hover {\n",
       "  /* fitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-3);\n",
       "}\n",
       "</style><div id=\"sk-container-id-1\" class=\"sk-top-container\"><div class=\"sk-text-repr-fallback\"><pre>BernoulliNB()</pre><b>In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook. <br />On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org.</b></div><div class=\"sk-container\" hidden><div class=\"sk-item\"><div class=\"sk-estimator fitted sk-toggleable\"><input class=\"sk-toggleable__control sk-hidden--visually\" id=\"sk-estimator-id-1\" type=\"checkbox\" checked><label for=\"sk-estimator-id-1\" class=\"sk-toggleable__label fitted sk-toggleable__label-arrow\"><div><div>BernoulliNB</div></div><div><a class=\"sk-estimator-doc-link fitted\" rel=\"noreferrer\" target=\"_blank\" href=\"https://scikit-learn.org/1.6/modules/generated/sklearn.naive_bayes.BernoulliNB.html\">?<span>Documentation for BernoulliNB</span></a><span class=\"sk-estimator-doc-link fitted\">i<span>Fitted</span></span></div></label><div class=\"sk-toggleable__content fitted\"><pre>BernoulliNB()</pre></div> </div></div></div></div>"
      ],
      "text/plain": [
       "BernoulliNB()"
      ]
     },
     "execution_count": 27,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "from sklearn.naive_bayes import BernoulliNB\n",
    "clf = BernoulliNB()\n",
    "\n",
    "X = df_train.iloc[:,:-1]\n",
    "Y = df_train.iloc[:,-1:]['cluster'].values\n",
    "\n",
    "clf.fit(X, Y)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 32,
   "id": "58187a1c-1642-4a02-a1a1-eb3b9f68b55b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "      cluster  cluster_predict\n",
      "2327        1                0\n",
      "835         2                0\n",
      "1433        0                0\n",
      "1183        0                0\n",
      "2742        1                0\n",
      "Prediction Accuracy: 0.5094\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "\n",
    "# Load the test data correctly using your own path\n",
    "df_test = pd.read_csv(r\"C:\\Users\\akank\\homework\\hw1\\data\\test.csv\", index_col=0)\n",
    "\n",
    "# Predict clusters\n",
    "df_test['cluster_predict'] = clf.predict(df_test.iloc[:, :-1])\n",
    "\n",
    "# Show few predictions\n",
    "print(df_test[['cluster', 'cluster_predict']].head())\n",
    "\n",
    "\n",
    "# Calculate prediction accuracy\n",
    "accuracy = 1 - error_rate\n",
    "print(f\"Prediction Accuracy: {accuracy:.4f}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 33,
   "id": "8b8fdb9e-585a-42e1-8e40-c367c3ee4b9a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Prediction Error Rate: 0.4906\n"
     ]
    }
   ],
   "source": [
    "\n",
    "# Calculate prediction error rate\n",
    "error_rate = df_test.query('cluster != cluster_predict').shape[0] / df_test.shape[0]\n",
    "print(f\"Prediction Error Rate: {error_rate:.4f}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ed19b27e-db2e-47ec-911b-05c8328d8d26",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
